a = " hello, World!"
print(a.upper())
print(a.lower())
print(a.strip())
print(a.replace("h", "J"))
print(a.split(","))   #Split into List [' hello', ' World!']
print(a.capitalize())
print(a.casefold())
print(a.count('l'))
print(a.endswith("!"))
print(a.find('W'))
print(a.index('W'))


print(a.isalpha())  # False (contains space, comma, and '!')
print(a.isalnum())  # False (contains space, comma, and '!')
print(a.isdigit())  # False (not numeric)
print(a.isdecimal())  # False (not numeric)
print(a.isidentifier())  # False (contains space, comma, etc.)
print(a.islower())
print(a.isupper())
print(a.startswith(" hello"))
print("-".join(['hello', 'world']))
print(a.ljust(20, "*"))
print(a.rjust(20, "*"))
print(a.swapcase())
print(a.title())
print(a.zfill(20))